services:
  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    volumes:
    volumes:
      - /home/deployer/docker/cloudflare.ini:/cloudflare.ini:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      sh -c "certbot certonly --dns-cloudflare \
        --dns-cloudflare-credentials /cloudflare.ini \
        --dns-cloudflare-propagation-seconds 60 \
        -d homer.dimykytyn.win \
        -d logs.dimykytyn.win \
        --email mykytyn.di@gmail.com \
        --agree-tos \
        --no-eff-email \
        --non-interactive || true;
      echo 'Starting renew loop...';
      while :; do
          certbot renew --dns-cloudflare --dns-cloudflare-credentials /cloudflare.ini --quiet;
          sleep 12h;
        done"
    restart: unless-stopped
    networks:
      - proxy_net

  homer:
    image: b4bz/homer
    container_name: homer
    hostname: homer
    volumes:
      - /homer:/www/assets
    ports:
      - "8080:8080"
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
    networks:
      - proxy_net

  victorialogs:
    image: victoriametrics/victoria-logs:v1.25.0
    container_name: victorialogs
    ports:
      - "9428:9428"
    volumes:
      - /victoria-logs/victoria-logs-data:/victoria-logs-data
    command: ["-storageDataPath=victoria-logs-data", "-loggerFormat=json", "-syslog.listenAddr.tcp=0.0.0.0:8094"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9428/health"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - proxy_net

  vector:
    image: timberio/vector:latest-debian
    container_name: vector
    ports:
      - "8686:8686"
    volumes:
      - /home/deployer/docker/vector:/etc/vector:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker:/var/lib/docker:ro
    user: root
    command: ["--config", "/etc/vector/vector.yaml"]
    restart: unless-stopped
    depends_on:
      victorialogs:
        condition: service_healthy
    networks:
      - proxy_net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot
      - homer 
      - victorialogs
    networks:
      - proxy_net
    
networks:
  proxy_net:
    driver: bridge
