output "ssh_key" {
  description = "ssh key generated by terraform"
  value       = tls_private_key.pk-rsa.private_key_pem
  sensitive = true
}

output "server_ip" {
  description = "Public IPv4 address of the provisioned server"
  value       = hcloud_server.main.ipv4_address
}